### model
model_name_or_path: /root/autodl-tmp/models/Qwen2.5-1.5B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0
lora_target: all


### quantization
# quantization_bit: 4 

### dataset
dataset: alpaca_en_demo  # video: mllm_video_demo
template: qwen
flash_attn: auto
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5_0_5b/lora/qwen2_5_0_5b_lora_adapter
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1    # 1000 * 0.1 = 100 steps
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
max_grad_norm: 1.0
ddp_timeout: 180000000
include_num_input_tokens_seen: True
optim: adamw_torch
# adapter_name_or_path: saves/Qwen2.5-0.5B/lora/qwen2_5_0_5B_lora_adapter     # 如果已经有训练好的适配器，可以加上这一行
## eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

